name: Sample

on:
  push:
    branches:
      - main
    # paths:
    #   - ".github/**"
    #   - "dist/**"
    #   - "examples/**"
  pull_request:
    branches:
      - "!main"
    # paths:
    #   - ".github/**"
    #   - "dist/**"
    #   - "examples/**"

jobs:
  sample:
    name: Sample step
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: ./
        with:
          config_file: examples/demo1.yml
      - uses: ./
        with:
          config_file: examples/demo2.yml.gpg
          gpg_passphrase: secret stuff
      - if: ${{ matrix.os == 'windows-latest' }}
        name: output on windows
        run: |
          echo '(mask) MASK_VALUE1'
          echo "(mask) GITHUB_REPOSITORY      : ${env:GITHUB_REPOSITORY}"
          echo "(mask) DUMMY1_TOKEN           : ${env:DUMMY1_TOKEN}"
          echo "       DUMMY1_NO_SECRET_TOKEN : ${env:DUMMY1_NO_SECRET_TOKEN}"
          echo "       DUMMY1_HOME            : ${env:DUMMY1_HOME}"
          echo "(mask) DUMMY2_TOKEN           : ${env:DUMMY2_TOKEN}"
          echo "ls -l examples/dest"
          ls examples/dest
          echo "ls -l ${env:HOME}/dest"
          ls ${env:HOME}/dest
          If ( "${env:DUMMY1_TOKEN}" -eq "DUMMY1_TOKEN_VALUE" ) {
            echo "assert ENV ... OK"
          } Else {
            echo "assert ENV ... NG"
            exit 1
          }
      - if: ${{ matrix.os != 'windows-latest' }}
        name: output on ubuntu or macOS
        run: |
          echo '(mask) MASK_VALUE1'
          echo "(mask) GITHUB_REPOSITORY      : ${GITHUB_REPOSITORY}"
          echo "(mask) DUMMY1_TOKEN           : ${DUMMY1_TOKEN}"
          echo "       DUMMY1_NO_SECRET_TOKEN : ${DUMMY1_NO_SECRET_TOKEN}"
          echo "       DUMMY1_HOME            : ${DUMMY1_HOME}"
          echo "(mask) DUMMY2_TOKEN           : ${DUMMY2_TOKEN}"
          echo "ls -l examples/dest"
          ls examples/dest
          echo "ls -l ${HOME}/dest"
          ls ${HOME}/dest
          if [ "${DUMMY1_TOKEN}" = "DUMMY1_TOKEN_VALUE" ]; then
            echo "assert ENV ... OK"
          else
            echo "assert ENV ... NG"
            exit 1
          fi
